---

- id: upy-package
  name: upy-package
  description: >
    Validate package.json file against changelog.md and setup.py for
    MicroPython mip installation
  entry: upy-package
  args:
    - "--setup_file=setup.py"
    - "--package_changelog_file=changelog.md"
    - "--package_file=package.json"
    - "--validate"
  language: python
  pass_filenames: false
  require_serial: true
