---

# This workflow will install Python dependencies, run tests and lint with a
# specific Python version
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python package

on:
  push:
    # branches: [ $default-branch ]
    branches-ignore:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install test dependencies
        run: |
          python -m pip install .[dev]
          python -m pip install .[test]
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with yamllint
        run: |
          yamllint .
      - name: Test with tox
        run: |
          python -m tox -e py
      - name: Install deploy dependencies
        run: |
          python -m pip install -U setuptools wheel build
          if [ -f requirements-deploy.txt ]; then pip install -r requirements-deploy.txt; fi
          pip install .
      - name: Build package
        run: |
          changelog2version \
            --changelog_file changelog.md \
            --version_file src/setup2upypackage/version.py \
            --version_file_type py \
            --debug
          python -m build .
      - name: Test built package
        run: |
          twine check dist/*
